# @package _group_

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-test
  #query_special_suffix: '?'

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-train

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-dev

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

webq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.webq-test

curatedtrec_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.curatedtrec-test

squad1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-train

squad1_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-dev

squad1_test:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-test

iddrs_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.iddrs-train

iddrs_test:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.iddrs-test